name: icached_network_image
description: "An advanced cached network image with handling"
version: 0.0.1
homepage:

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2


flutter:

  assets:
    - packages/icached_network_image/assets/placeholder.png
